# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# Default recipe: format (rewrites, decides nothing; `just fix` is the mutable one)
default: fmt

# >>> justx:fmt (managed) — `j @upgrade` re-syncs; remove these fences to take over
# format Go code - rewrites to canonical form
fmt:
    go tool standardgo fmt ./...
# <<< justx:fmt

# >>> justx:lint (managed) — `j @upgrade` re-syncs; remove these fences to take over
# lint Go code - reports findings, changes nothing
lint:
    go tool standardgo ./...
# <<< justx:lint

# >>> justx:fix (managed) — `j @upgrade` re-syncs; remove these fences to take over
# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go tool standardgo ./... --fix
# <<< justx:fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# >>> justx:ci (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run all checks - read-only, safe for CI
ci: lint test
# <<< justx:ci

# --- Everything below is hand-written (outside the fences, so `@upgrade` never
# --- touches it). Recipes are named in the mapped form and typed in the
# --- expressive one: `demo--list` is invoked as `j demo:list`.

# Keep go.mod/go.sum tidy - what `j ready?` tells you to run
tidy:
    go mod tidy

# Install justx into GOPATH/bin - rebuilds the binary your `j` alias runs
install:
    go install ./cmd/justx

# Full install: build the binary and wire the `j` / `just` shell aliases
install--shell:     # <- call with: j install:shell
    ./install.sh

# Remove the binary and the alias block from your rc file
uninstall:
    ./uninstall.sh

# Run justx from source without installing, e.g. `just run @version`
run *ARGS:
    @go run ./cmd/justx {{ARGS}}

# Force a full rebuild, ignoring the build cache
build-x:            # <- call with: j build!
    go build -a ./...

# --- Dogfooding ---
#
# These run justx against this very repo, so a regression in the router or the
# scaffolder shows up while you are still working on it.

# List recipes through justx: names reverse-translate to the expressive form
demo--list:         # <- call with: j demo:list
    @go run ./cmd/justx --list

# Scaffold a justfile into a throwaway Go project and print it
demo--init:         # <- call with: j demo:init
    #!/usr/bin/env bash
    set -euo pipefail
    bin="$(mktemp -d)"
    dir="$(mktemp -d)"
    trap 'rm -rf "$bin" "$dir"' EXIT
    go build -o "$bin/justx" ./cmd/justx
    cd "$dir"
    go mod init justx-demo >/dev/null
    "$bin/justx" @init --yes
    echo
    cat justfile

# Ready to tag a release? - green ci, tidy modules, clean tree. Reports, never fixes.
[no-exit-message]
ready-q: ci         # <- call with: j ready?
    #!/usr/bin/env bash
    set -uo pipefail
    rc=0
    if go mod tidy -diff >/dev/null 2>&1; then
        echo "✓ go.mod / go.sum tidy"
    else
        echo "✗ go.mod / go.sum need \`just tidy\`"; rc=1
    fi
    if [ -z "$(git status --porcelain)" ]; then
        echo "✓ working tree clean"
    else
        echo "✗ working tree dirty"; rc=1
    fi
    exit $rc
