// Package scaffold composes selected modules into a justfile, wrapping each
// module's recipes in `# >>> justx:<id>` / `# <<< justx:<id>` provenance fences
// so v2's @upgrade can re-sync managed regions without clobbering user edits.
package scaffold

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/amberpixels/just-x/internal/detect"
	"github.com/amberpixels/just-x/internal/modules"
)

const header = `# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between ` + "`# >>> justx:<id>`" + ` and ` + "`# <<< justx:<id>`" + ` are managed by justx.
# Edit anything outside the fences freely; ` + "`j @upgrade`" + ` (v2) re-syncs managed blocks.
`

// Compose renders the chosen modules into justfile text for the given project.
// Modules are emitted in the order provided.
func Compose(p detect.Project, mods []modules.Module) (string, error) {
	var b strings.Builder
	b.WriteString(header)

	for _, m := range mods {
		body, err := render(m, p)
		if err != nil {
			return "", fmt.Errorf("module %s: %w", m.ID, err)
		}
		b.WriteString("\n")
		b.WriteString(wrapFence(m.ID, body))
	}

	return b.String(), nil
}

// render executes a module's recipe template against the project. [[ ]] delims
// keep just's own {{ }} interpolation intact.
func render(m modules.Module, p detect.Project) (string, error) {
	tmpl, err := template.New(m.ID).Delims("[[", "]]").Parse(m.Recipes)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, p); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// wrapFence surrounds a module body with its provenance fences.
func wrapFence(id, body string) string {
	body = strings.Trim(body, "\n")
	return fmt.Sprintf(
		"# >>> justx:%s (managed) — `j @upgrade` re-syncs; remove these fences to take over\n%s\n# <<< justx:%s\n",
		id, body, id,
	)
}
