package scaffold

import (
	"strings"
	"testing"

	"github.com/amberpixels/just-x/internal/detect"
	"github.com/amberpixels/just-x/internal/modules"
)

func TestComposeGo(t *testing.T) {
	p := detect.Project{Stack: detect.StackGo}
	mods := modules.ForProject(p)

	out, err := Compose(p, mods)
	if err != nil {
		t.Fatal(err)
	}

	// Header present.
	if !strings.Contains(out, "generated by justx") {
		t.Errorf("missing header:\n%s", out)
	}
	// Each module fenced with matching begin/end markers.
	for _, id := range []string{"fmt", "lint", "test", "build", "ci"} {
		begin := "# >>> justx:" + id
		end := "# <<< justx:" + id
		if !strings.Contains(out, begin) {
			t.Errorf("missing begin fence for %q", id)
		}
		if !strings.Contains(out, end) {
			t.Errorf("missing end fence for %q", id)
		}
	}
	// Go-specific recipe content.
	if !strings.Contains(out, "go test ./...") {
		t.Errorf("missing go test recipe:\n%s", out)
	}
	if !strings.Contains(out, "golangci-lint run") {
		t.Errorf("missing lint recipe:\n%s", out)
	}
}

func TestComposeNodeUsesPackageManager(t *testing.T) {
	p := detect.Project{Stack: detect.StackNode, PackageManager: "pnpm"}
	mods := modules.ForProject(p)

	out, err := Compose(p, mods)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "pnpm run test") {
		t.Errorf("expected pnpm-rendered recipe, got:\n%s", out)
	}
	if strings.Contains(out, "[[.PackageManager]]") {
		t.Errorf("template delimiter left unrendered:\n%s", out)
	}
}

// A module whose recipe contains just's own {{ }} interpolation must pass
// through untouched, since we render with [[ ]] delimiters.
func TestComposePreservesJustInterpolation(t *testing.T) {
	p := detect.Project{Stack: detect.StackGo}
	custom := []modules.Module{{
		ID:      "greet",
		Recipes: "greet name:\n    @echo \"hi {{name}}\"\n",
	}}
	out, err := Compose(p, custom)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "{{name}}") {
		t.Errorf("just interpolation was mangled:\n%s", out)
	}
}

func TestComposeFenceOrdering(t *testing.T) {
	p := detect.Project{Stack: detect.StackGo}
	out, err := Compose(p, modules.ForProject(p))
	if err != nil {
		t.Fatal(err)
	}
	// For each module the begin fence must come before its end fence.
	for _, id := range []string{"fmt", "ci"} {
		bi := strings.Index(out, "# >>> justx:"+id)
		ei := strings.Index(out, "# <<< justx:"+id)
		if bi < 0 || ei < 0 || bi >= ei {
			t.Errorf("fence ordering wrong for %q: begin=%d end=%d", id, bi, ei)
		}
	}
}
